apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      component: auth
  template:
    metadata:
      labels:
        component: auth
    spec:
      containers:
        - name: auth
          image: oguzdocker/auth
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  #type: ClusterIp this is default
  selector:
    component: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3015
      targetPort: 3015